### PR TITLE
Fix storage vulnerability

### PR DESCRIPTION
**Pull request by joepetrowski**
The `buy_kitty` function modified storage before all checks were completed. 
```rust
<balances::Module<T>>::make_transfer(&sender, &owner, kitty_price)?; // <-- modifies storage

Self::_transfer_from(owner.clone(), sender.clone(), kitty_id)?; // <-- !!! ? can return Err
```
Added an ensure function to perform checks before transferring any balance, so that when you buy that 18,446,744,073,709,551,616th kitty, you won't pay before overflowing the Kitties array!

### CODE REVIEW

**Comment by shawntabrizi** [comment]
@joepetrowski we chatted in person, and this is not a storage vulnerability because the TotalKittyCount is bounded by u64, so no user can then acquire an OwnedKittyCount of greater than u64, thus we do not need to make this check.

However, I agree with you that we could be better bout designing our functions to follow the "Verify, then Write" pattern, and I look forward to your upcoming update to reflect this

**Comment by shawntabrizi** [comment]
Hey @joepetrowski , I talked with @thiolliere and I think that this is also not even a good general solution.

Here your `ensure_owner_can_transfer` does its verification using values stored in the blockchain storage. If you write other functions which do the same, then they may be using incorrect values to do the check when these checks are serialized.

For example, when you check an increment in on `ensure` method, and then do it again in another `ensure` method, you will have only checked a single increment from the storage, and not two like you should.

I think this calls out a general problem with this pattern when building runtimes. Instead, I think we should not refactor into two halves, and just make sure that the subsequent function can never fail by writing custom checks before the functions are called. As a result of that, we may even want to turn these functions into just methods to write to storage... but I really dont know.

Either way, it seems that trying to build these functions *in general* is quite hard on the substrate framework

**Comment by joepetrowski** [comment]
> If you write other functions which do the same, then they may be using incorrect values to do the check when these checks are serialized.

Yes, true. My opinion is that these functions are implemented directly in the runtime, not imported from a module. It's up to developer to ensure that the output from a previous check (e.g. `checked_add`) is carried into subsequent checks that check the same storage value.

**Comment by shawntabrizi** [comment]
Fixed with: https://github.com/shawntabrizi/substratekitties/commit/2a4735c764d1c5cff5f74138395886212e44f236

**Pull request closed without merging**
